import { ArrowUpRight, CalendarClock, Globe2, MapPin, Sparkles } from "lucide-react";

const OPPORTUNITIES = [
  { title: "Stage Backend TypeScript", organization: "Northstar Labs", type: "INTERNSHIP", location: "Remote · Europe", deadline: "Dans 12 jours", skills: ["TypeScript", "Node.js", "PostgreSQL"], match: "92%" },
  { title: "Hackathon Climate Data", organization: "Open Data House", type: "HACKATHON", location: "Paris · Hybride", deadline: "Dans 18 jours", skills: ["Python", "Data", "Teamwork"], match: "84%" },
  { title: "Bourse Open Source", organization: "Code Commons", type: "SCHOLARSHIP", location: "International", deadline: "30 avril 2027", skills: ["Git", "Documentation", "Community"], match: "78%" },
  { title: "Research Assistant · Vision", organization: "Vision Lab", type: "RESEARCH", location: "Dakar · Sur place", deadline: "Dans 27 jours", skills: ["Python", "PyTorch", "Research"], match: "76%" },
];

export function OpportunitiesScreen() {
  return <div className="flex-1 overflow-y-auto tt-scrollbar"><div className="mx-auto max-w-6xl px-4 py-8 md:px-8"><header className="mb-8 max-w-3xl tt-fade-up"><p className="tt-label mb-3">Opportunities / passer à l'action</p><h1 className="text-3xl font-extrabold md:text-5xl">Le prochain mouvement compte.</h1><p className="mt-4 text-sm leading-relaxed text-muted-foreground">Stages, bourses, hackathons et recherche sélectionnés selon vos compétences, vos objectifs et votre contexte.</p></header><div className="mb-5 flex flex-wrap gap-2"><span className="tt-chip tt-chip-active">Pour vous</span><span className="tt-chip">Stages</span><span className="tt-chip">Hackathons</span><span className="tt-chip">Remote</span><span className="tt-chip">Deadline proche</span></div><div className="grid gap-4 lg:grid-cols-2 tt-stagger">{OPPORTUNITIES.map((item) => <article key={item.title} className="tt-card tt-card-hover p-5"><div className="flex items-start justify-between gap-4"><div><span className="tt-label text-primary">{item.type}</span><h2 className="mt-2 text-lg font-extrabold">{item.title}</h2><p className="mt-1 text-xs font-semibold text-accent">{item.organization}</p></div><div className="border border-primary px-2 py-1 text-center"><strong className="block text-sm text-primary">{item.match}</strong><span className="text-[9px] uppercase tracking-widest text-muted-foreground">match</span></div></div><div className="mt-5 flex flex-wrap gap-3 text-xs text-muted-foreground"><span className="flex items-center gap-1"><MapPin size={13} /> {item.location}</span><span className="flex items-center gap-1"><CalendarClock size={13} /> {item.deadline}</span></div><div className="mt-4 flex flex-wrap gap-1.5">{item.skills.map((skill) => <span key={skill} className="tt-chip text-[10px]">{skill}</span>)}</div><div className="mt-5 flex items-center justify-between border-t border-border pt-3"><span className="flex items-center gap-1.5 text-[11px] text-muted-foreground"><Sparkles size={13} className="text-primary" /> Pourquoi : 3 compétences correspondent</span><button className="tt-btn tt-btn-brand gap-1 px-3 py-1.5 text-xs">Ouvrir <ArrowUpRight size={13} /></button></div></article>)}</div><div className="mt-8 tt-card flex items-center gap-4 p-5"><Globe2 className="shrink-0 text-accent" size={22} /><div><h2 className="font-extrabold">Une opportunité n'est pas qu'une offre.</h2><p className="mt-1 text-xs text-muted-foreground">TechTalk relie compétences, projets, personnes et contexte pour expliquer pourquoi elle mérite votre attention.</p></div></div></div></div>;
}
