import { ArrowUpRight, BriefcaseBusiness, GraduationCap, MessageCircle, UserPlus } from "lucide-react";

const PEOPLE = [
  { name: "Amina Diallo", role: "Étudiante · Data/IA", proof: "Publie des notebooks reproductibles sur la classification", tags: ["Python", "ML", "Research"], context: "Université de Dakar" },
  { name: "Lucas Martin", role: "Ingénieur backend", proof: "Maintient 3 librairies open source et documente ses choix", tags: ["Go", "Systems", "Open source"], context: "Lyon · disponible pour mentorat" },
  { name: "Nora Benali", role: "Frontend builder", proof: "Construit des interfaces accessibles pour des campus", tags: ["React", "Design", "Accessibility"], context: "Paris · projet collaboratif" },
  { name: "Ethan Okafor", role: "Compétiteur", proof: "Partage ses méthodes de résolution après chaque contest", tags: ["C++", "Algorithms", "CP"], context: "Lagos · communauté active" },
];

export function PeopleScreen() {
  return <div className="flex-1 overflow-y-auto tt-scrollbar"><div className="mx-auto max-w-6xl px-4 py-8 md:px-8"><header className="mb-8 max-w-2xl tt-fade-up"><p className="tt-label mb-3">Connect / preuves observables</p><h1 className="text-3xl font-extrabold md:text-5xl">Les personnes derrière le travail.</h1><p className="mt-4 text-sm leading-relaxed text-muted-foreground">Rencontrez des étudiants, builders, mentors et contributeurs par leurs projets, leurs sujets et leur manière de partager.</p></header><div className="grid gap-4 md:grid-cols-2 tt-stagger">{PEOPLE.map((person) => <article key={person.name} className="tt-card tt-card-hover p-5"><div className="flex items-start gap-3"><span className="tt-brand-tile h-12 w-12 shrink-0 rounded-full text-sm font-extrabold">{person.name.split(" ").map((part) => part[0]).join("")}</span><div className="min-w-0"><h2 className="text-base font-extrabold">{person.name}</h2><p className="text-xs text-accent">{person.role}</p><p className="mt-1 text-[11px] text-muted-foreground">{person.context}</p></div></div><div className="mt-5 border-l-2 border-primary pl-3"><p className="text-sm leading-relaxed">{person.proof}</p></div><div className="mt-5 flex flex-wrap gap-1.5">{person.tags.map((tag) => <span key={tag} className="tt-chip text-[10px]">{tag}</span>)}</div><div className="mt-5 flex gap-2"><button className="tt-btn tt-btn-secondary gap-1.5 px-3 py-2 text-xs"><UserPlus size={13} /> Suivre</button><button className="tt-btn tt-btn-ghost gap-1.5 px-3 py-2 text-xs"><MessageCircle size={13} /> Écrire</button><button className="tt-btn tt-btn-ghost ml-auto p-2" aria-label="Voir le profil"><ArrowUpRight size={14} /></button></div></article>)}</div><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="tt-card p-5"><GraduationCap className="mb-3 text-accent" size={20} /><h2 className="font-extrabold">Campus à rejoindre</h2><p className="mt-1 text-xs text-muted-foreground">Trouvez les personnes qui apprennent près de vous.</p></div><div className="tt-card p-5"><BriefcaseBusiness className="mb-3 text-primary" size={20} /><h2 className="font-extrabold">Mentors et collaborateurs</h2><p className="mt-1 text-xs text-muted-foreground">Faites émerger les bons contacts à partir de vos objectifs.</p></div></div></div></div>;
}
