import { ExternalLink, GitBranch, Github, Plus, Star } from "lucide-react";

const PROJECTS = [
  { name: "Lumen Search", author: "Maya K.", description: "Moteur de recherche local, rapide et lisible pour des notes techniques.", tags: ["Rust", "Search", "Systems"], stars: 128, status: "En cours" },
  { name: "Campus OS", author: "Collectif ENSA", description: "Un kit open source pour organiser ressources, événements et entraide étudiante.", tags: ["TypeScript", "React", "Campus"], stars: 84, status: "Ouvert" },
  { name: "Tiny Vision Lab", author: "Noah A.", description: "Expériences reproductibles autour de la vision par ordinateur sur petits modèles.", tags: ["Python", "AI", "Research"], stars: 56, status: "Prototype" },
  { name: "API Atlas", author: "Samir B.", description: "Une collection d'APIs Fastify documentées par des cas d'usage réels.", tags: ["Node.js", "Fastify", "REST"], stars: 41, status: "Actif" },
];

export function ProjectsScreen() {
  return <div className="flex-1 overflow-y-auto tt-scrollbar"><div className="mx-auto max-w-6xl px-4 py-8 md:px-8"><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><header className="tt-fade-up"><p className="tt-label mb-3">Build / preuves de travail</p><h1 className="text-3xl font-extrabold md:text-5xl">Les idées deviennent visibles.</h1><p className="mt-4 max-w-xl text-sm leading-relaxed text-muted-foreground">Découvrez des projets par technologie, difficulté et intention. Pas de classement de génie : des traces, des choix et des choses construites.</p></header><button className="tt-btn tt-btn-brand shrink-0 gap-2 px-4 py-2.5 text-xs"><Plus size={14} /> Ajouter un projet</button></div><div className="mb-5 flex gap-2 overflow-x-auto pb-1"><span className="tt-chip tt-chip-active">Tous les projets</span><span className="tt-chip">Open source</span><span className="tt-chip">Nouveaux</span><span className="tt-chip">Par technologie</span></div><div className="grid gap-4 md:grid-cols-2 tt-stagger">{PROJECTS.map((project) => <article key={project.name} className="tt-card tt-card-hover p-5"><div className="flex items-start justify-between gap-3"><span className="tt-brand-tile h-10 w-10 rounded-xl"><Github size={18} /></span><span className="tt-chip text-[10px]">{project.status}</span></div><h2 className="mt-5 text-lg font-extrabold">{project.name}</h2><p className="mt-1 text-xs font-semibold text-accent">par {project.author}</p><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{project.description}</p><div className="mt-5 flex flex-wrap gap-1.5">{project.tags.map((tag) => <span key={tag} className="tt-chip text-[10px]">{tag}</span>)}</div><div className="mt-5 flex items-center gap-4 border-t border-border pt-3 text-xs text-muted-foreground"><span className="flex items-center gap-1"><Star size={13} className="text-primary" /> {project.stars}</span><span className="flex items-center gap-1"><GitBranch size={13} /> 12 contributions</span><button className="tt-btn tt-btn-ghost ml-auto gap-1 px-3 py-1.5 text-[11px]">Voir <ExternalLink size={12} /></button></div></article>)}</div></div></div>;
}
